site_name: Shadow Experimental Documentation
repo_url: https://github.com/shadow-robot/sr_experimental_documentation.git

copyright: "Copyright © 2018, 2019 Shadow Robot Company"
theme: readthedocs

pages:
- Home: index.md
- 'Arm and Hand': 
    - 'Setting up a real system': 
        - 'Setting up the table': 'user_guide/1_1_setting_up_the_table.md'
        - 'Setting up the arm': 'user_guide/1_2_setting_up_arm.md'
        - 'Setting up the hand': 'user_guide/1_3_setting_up_hand.md'
        - 'Installing the software': 'user_guide/1_4_Installing_the_software.md'
    - 'Setting up a simulated system': 'user_guide/1_5_setting_up_simulation.md'
    - 'Software description': 'user_guide/1_6_software_description.md'
- 'Bimanual system': 'user_guide/2_bimanual_system.md'
