site_name: Shadow Experimental Documentation
repo_url: https://github.com/shadow-robot/sr_experimental_documentation.git

copyright: "Copyright © 2018, 2019 Shadow Robot Company"
theme: readthedocs

pages:
- Home: index.md
- User Documentation:
    - 'UR Arm and Hand': 'user_guide/1_arm_and_hand.md'
    - 'Bimanual system': 'user_guide/2_bimanual_system.md'
    - 'Teleoperation': 'user_guide/3_teleoperation.md'
